// frontend/src/app/components/image-carousel/image-carousel.component.ts
import { CommonModule } from '@angular/common';
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-image-carousel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './image-carousel.component.html',
  styleUrl: './image-carousel.component.scss',
})
export class ImageCarouselComponent {
  images = input<string[]>([]);
  isAdmin = input<boolean>(false);
  carId = input<number | null>(null);
  showThumbnails = input<boolean>(true);
  onRemoveImage = output<string>();
  onImageClick = output<string>();

  currentIndex: number = 0;
  selectedImage: string | null = null;

  get shouldRender(): boolean {
    const imgs = this.images();
    return !!imgs && imgs.length > 0;
  }

  get shouldShowNavigation(): boolean {
    const imgs = this.images();
    return !!imgs && imgs.length > 1;
  }

  nextImage(): void {
    const imgs = this.images();
    if (imgs && imgs.length > 1) {
      this.currentIndex = (this.currentIndex + 1) % imgs.length;
    }
  }

  prevImage(): void {
    const imgs = this.images();
    if (imgs && imgs.length > 1) {
      this.currentIndex = this.currentIndex === 0 ? imgs.length - 1 : this.currentIndex - 1;
    }
  }

  handleImageClick(imageUrl: string): void {
    // Always show modal for full-size image
    this.selectedImage = imageUrl;

    // Emit event for parent component (for listing view navigation)
    this.onImageClick.emit(imageUrl);
  }

  handleThumbnailClick(index: number, event: Event): void {
    event.stopPropagation();
    this.currentIndex = index;
  }

  handleModalClose(): void {
    this.selectedImage = null;
  }

  handleModalImageClick(event: Event): void {
    event.stopPropagation();
  }

  handleRemoveImage(imageUrl: string): void {
    this.onRemoveImage.emit(imageUrl);
  }
}

<!-- Render only if images exist -->
<div *ngIf="shouldRender" class="mt-4">
  <!-- Main Carousel -->
  <div class="relative">
    <div class="overflow-hidden relative h-36 rounded-lg bg-zinc-700">
      <img
        [src]="images()[currentIndex]"
        [alt]="'Car image ' + (currentIndex + 1)"
        class="object-contain w-full h-full cursor-pointer"
        (click)="handleImageClick(images()[currentIndex]); $event.stopPropagation()"
      />

      <!-- Navigation buttons -->
      <div *ngIf="shouldShowNavigation">
        <button
          (click)="prevImage(); $event.stopPropagation()"
          class="flex absolute left-2 top-1/2 justify-center items-center w-8 h-8 text-white bg-black bg-opacity-50 rounded-full transition-opacity transform -translate-y-1/2 hover:bg-opacity-75"
          title="Previous image"
        >
          ‹
        </button>
        <button
          (click)="nextImage(); $event.stopPropagation()"
          class="flex absolute right-2 top-1/2 justify-center items-center w-8 h-8 text-white bg-black bg-opacity-50 rounded-full transition-opacity transform -translate-y-1/2 hover:bg-opacity-75"
          title="Next image"
        >
          ›
        </button>
      </div>

      <!-- Remove button for admin -->
      <button
        *ngIf="isAdmin()"
        (click)="handleRemoveImage(images()[currentIndex]); $event.stopPropagation()"
        class="flex absolute top-2 right-2 justify-center items-center w-6 h-6 text-sm text-white bg-red-500 rounded-full transition-colors hover:bg-red-600"
        title="Remove image"
      >
        ×
      </button>
    </div>

    <!-- Image counter -->
    <div
      class="absolute bottom-2 left-2 px-2 py-1 text-sm text-white bg-black bg-opacity-50 rounded"
    >
      {{ currentIndex + 1 }} / {{ images().length }}
    </div>
  </div>

  <!-- Thumbnail navigation -->
  <div
    *ngIf="shouldShowNavigation && showThumbnails()"
    class="flex overflow-x-auto gap-1 justify-center mt-2"
  >
    <button
      *ngFor="let imageUrl of images(); let index = index"
      (click)="handleThumbnailClick(index, $event); $event.stopPropagation()"
      [class]="
        'flex-shrink-0 w-12 h-8 rounded border-2 transition-all ' +
        (index === currentIndex
          ? 'border-blue-500 opacity-100'
          : 'border-zinc-600 opacity-60 hover:bg-opacity-80')
      "
    >
      <img
        [src]="imageUrl"
        [alt]="'Thumbnail ' + (index + 1)"
        class="object-cover w-full h-full rounded"
      />
    </button>
  </div>

  <!-- Modal for full-size image -->
  <div
    *ngIf="selectedImage"
    class="flex fixed inset-0 z-50 justify-center items-center bg-black bg-opacity-75"
    (click)="handleModalClose(); $event.stopPropagation()"
  >
    <div class="flex flex-col p-6 w-full max-w-7xl h-full max-h-full">
      <!-- Main image with navigation -->
      <div class="relative flex-1 mb-4 min-h-0">
        <div class="overflow-auto relative h-full rounded-lg bg-zinc-800">
          <div class="flex justify-center items-center p-4 h-full min-h-full">
            <img
              [src]="images()[currentIndex]"
              [alt]="'Car image ' + (currentIndex + 1)"
              class="object-contain w-full h-full"
              (click)="handleModalImageClick($event)"
            />
          </div>

          <!-- Navigation buttons -->
          <div *ngIf="shouldShowNavigation">
            <button
              (click)="prevImage(); $event.stopPropagation()"
              class="flex absolute left-2 top-1/2 justify-center items-center w-12 h-12 text-white bg-black bg-opacity-50 rounded-full transition-opacity transform -translate-y-1/2 hover:bg-opacity-75"
              title="Previous image"
            >
              ‹
            </button>
            <button
              (click)="nextImage(); $event.stopPropagation()"
              class="flex absolute right-2 top-1/2 justify-center items-center w-12 h-12 text-white bg-black bg-opacity-50 rounded-full transition-opacity transform -translate-y-1/2 hover:bg-opacity-75"
              title="Next image"
            >
              ›
            </button>
          </div>

          <!-- Image counter -->
          <div
            class="absolute bottom-2 left-2 px-3 py-1 text-sm text-white bg-black bg-opacity-50 rounded"
          >
            {{ currentIndex + 1 }} / {{ images().length }}
          </div>
        </div>
      </div>

      <!-- Thumbnail navigation -->
      <div
        *ngIf="shouldShowNavigation"
        class="flex overflow-x-auto flex-shrink-0 gap-2 justify-center"
      >
        <button
          *ngFor="let imageUrl of images(); let index = index"
          (click)="handleThumbnailClick(index, $event); $event.stopPropagation()"
          [class]="
            'flex-shrink-0 w-20 h-16 rounded border-2 transition-all ' +
            (index === currentIndex
              ? 'border-blue-500 opacity-100'
              : 'border-zinc-0 opacity-60 hover:opacity-80')
          "
        >
          <img
            [src]="imageUrl"
            [alt]="'Thumbnail ' + (index + 1)"
            class="object-cover w-full h-full rounded"
          />
        </button>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/ImageCarousel.jsx
import { useState } from "react";

const ImageCarousel = ({ images, onRemoveImage, carId, isAdmin }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedImage, setSelectedImage] = useState(null);

  if (!images || images.length === 0) {
    return null;
  }

  const nextImage = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  const prevImage = () => {
    setCurrentIndex((prevIndex) => (prevIndex - 1 + images.length) % images.length);
  };

  const handleImageClick = (imageUrl) => {
    setSelectedImage(imageUrl);
  };

  const handleRemoveImage = async (imageUrl) => {
    if (!confirm("Are you sure you want to remove this image?")) return;

    try {
      const token = localStorage.getItem("token");
      const response = await fetch(
        `http://localhost:8080/api/cars/${carId}/gallery?imageUrl=${encodeURIComponent(imageUrl)}`,
        {
          method: "DELETE",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (response.ok) {
        onRemoveImage(imageUrl);
        // Reset to first image if we're removing the current one
        if (images[currentIndex] === imageUrl) {
          setCurrentIndex(0);
        }
      } else {
        alert("Error removing image");
      }
    } catch {
      alert("Network error");
    }
  };

  return (
    <div className="mt-4">
      <h3 className="text-lg font-semibold text-white mb-3">Image Gallery</h3>

      {/* Main Carousel */}
      <div className="relative">
        <div className="relative h-64 bg-zinc-700 rounded-lg overflow-hidden">
          <img
            src={images[currentIndex]}
            alt={`Car image ${currentIndex + 1}`}
            className="w-full h-full object-cover"
            onClick={() => handleImageClick(images[currentIndex])}
          />

          {/* Navigation buttons */}
          {images.length > 1 && (
            <>
              <button
                onClick={prevImage}
                className="absolute left-2 top-1/2 transform -translate-y-1/2 bg-black bg-opacity-50 text-white rounded-full w-10 h-10 flex items-center justify-center hover:bg-opacity-75 transition-opacity"
                title="Previous image"
              >
                ‹
              </button>
              <button
                onClick={nextImage}
                className="absolute right-2 top-1/2 transform -translate-y-1/2 bg-black bg-opacity-50 text-white rounded-full w-10 h-10 flex items-center justify-center hover:bg-opacity-75 transition-opacity"
                title="Next image"
              >
                ›
              </button>
            </>
          )}

          {/* Remove button for admin */}
          {isAdmin && (
            <button
              onClick={() => handleRemoveImage(images[currentIndex])}
              className="absolute top-2 right-2 bg-red-500 text-white rounded-full w-8 h-8 flex items-center justify-center text-sm hover:bg-red-600 transition-colors"
              title="Remove image"
            >
              ×
            </button>
          )}
        </div>

        {/* Image counter */}
        <div className="absolute bottom-2 left-2 bg-black bg-opacity-50 text-white px-2 py-1 rounded text-sm">
          {currentIndex + 1} / {images.length}
        </div>
      </div>

      {/* Thumbnail navigation */}
      {images.length > 1 && (
        <div className="flex gap-2 mt-3 overflow-x-auto">
          {images.map((imageUrl, index) => (
            <button
              key={index}
              onClick={(e) => {
                e.stopPropagation();
                setCurrentIndex(index);
              }}
              className={`flex-shrink-0 w-16 h-12 rounded border-2 transition-all ${
                index === currentIndex
                  ? "border-blue-500 opacity-100"
                  : "border-zinc-600 opacity-60 hover:opacity-80"
              }`}
            >
              <img
                src={imageUrl}
                alt={`Thumbnail ${index + 1}`}
                className="w-full h-full object-cover rounded"
              />
            </button>
          ))}
        </div>
      )}

      {/* Modal for full-size image */}
      {selectedImage && (
        <div
          className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50"
          onClick={() => setSelectedImage(null)}
        >
          <div className="max-w-4xl max-h-full p-4">
            <img
              src={selectedImage}
              alt="Full size"
              className="max-w-full max-h-full object-contain"
              onClick={(e) => e.stopPropagation()}
            />
          </div>
        </div>
      )}
    </div>
  );
};

export default ImageCarousel;
