// frontend/src/app/components/login-form/login-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Auth } from '../../services/auth';

interface LoginData {
  username: string;
  role: string;
}

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login-form.component.html',
  styleUrl: './login-form.component.scss',
})
export class LoginFormComponent {
  username: string = '';
  password: string = '';
  loading: boolean = false;
  error: string = '';

  onLogin = output<LoginData>();

  constructor(private auth: Auth) {}

  async handleSubmit(event: Event) {
    event.preventDefault();
    this.loading = true;
    this.error = '';

    try {
      const data = await this.auth.login(this.username, this.password);
      this.onLogin.emit({ username: data.username, role: data.role });
    } catch (error) {
      this.error = (error as Error)?.message || 'Login failed';
    } finally {
      this.loading = false;
    }
  }
}

<div class="p-6 mb-6 rounded-lg border shadow-md bg-zinc-800 border-zinc-700">
  <h2 class="mb-6 text-2xl font-bold text-center text-white">Admin Login</h2>

  <!-- Error message -->
  <div *ngIf="error" class="p-3 mb-4 text-red-300 bg-red-900 rounded border border-red-600">
    {{ error }}
  </div>

  <!-- Login form -->
  <form (ngSubmit)="handleSubmit($event)">
    <div class="mb-4">
      <label class="block mb-2 text-sm font-bold text-zinc-300">Username</label>
      <input
        type="text"
        [(ngModel)]="username"
        name="username"
        class="p-2 w-full text-black bg-white rounded border border-zinc-600 focus:outline-none focus:border-blue-500"
        required
      />
    </div>

    <div class="mb-6">
      <label class="block mb-2 text-sm font-bold text-zinc-300">Password</label>
      <input
        type="password"
        [(ngModel)]="password"
        name="password"
        class="p-2 w-full text-black bg-white rounded border border-zinc-600 focus:outline-none focus:border-blue-500"
        required
      />
    </div>

    <button
      type="submit"
      [disabled]="loading"
      class="px-4 py-2 w-full font-bold text-white bg-blue-500 rounded hover:bg-blue-700 disabled:opacity-50"
    >
      {{ loading ? 'Logging in...' : 'Login' }}
    </button>
  </form>

  <!-- Demo credentials -->
  <div class="mt-4 text-sm text-center text-zinc-400">
    <p>Demo credentials:</p>
    <p>Username: admin</p>
    <p>Password: admin123</p>
  </div>
</div>

// frontend/src/components/LoginForm.jsx
import { useState } from "react";

const LoginForm = ({ onLogin }) => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      const response = await fetch("http://localhost:8080/api/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });

      const data = await response.json();

      if (response.ok) {
        localStorage.setItem("token", data.token);
        localStorage.setItem("user", JSON.stringify({ username: data.username, role: data.role }));
        onLogin(data);
      } else {
        setError(data.message || "Login failed");
      }
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 mb-6 rounded-lg border shadow-md bg-zinc-800 border-zinc-700">
      <h2 className="mb-6 text-2xl font-bold text-center text-white">Admin Login</h2>

      {error && (
        <div className="p-3 mb-4 text-red-300 bg-red-900 rounded border border-red-600">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit}>
        <div className="mb-4">
          <label className="block mb-2 text-sm font-bold text-zinc-300">Username</label>
          <input
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="p-2 w-full text-black bg-white rounded border border-zinc-600 focus:outline-none focus:border-blue-500"
            required
          />
        </div>

        <div className="mb-6">
          <label className="block mb-2 text-sm font-bold text-zinc-300">Password</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="p-2 w-full text-black bg-white rounded border border-zinc-600 focus:outline-none focus:border-blue-500"
            required
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="px-4 py-2 w-full font-bold text-white bg-blue-500 rounded hover:bg-blue-700 disabled:opacity-50"
        >
          {loading ? "Logging in..." : "Login"}
        </button>
      </form>

      <div className="mt-4 text-sm text-center text-zinc-400">
        <p>Demo credentials:</p>
        <p>Username: admin</p>
        <p>Password: admin123</p>
      </div>
    </div>
  );
};

export default LoginForm;
