// frontend/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CarFormComponent } from './components/car-form/car-form.component';
import { ImageCarouselComponent } from './components/image-carousel/image-carousel.component';
import { LoginFormComponent } from './components/login-form/login-form.component';
import { Auth } from './services/auth';
import { Car as CarService } from './services/car';

interface Car {
  id: number;
  brand: string;
  model: string;
  productionYear: number;
  price: number;
  fuelType: string;
  mileage: number;
  engineCapacity: number;
  transmission: string;
  description?: string;
  createdAt?: Date;
  updatedAt?: Date;
  imageGallery?: string[];
}

interface User {
  username: string;
  role: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    CarFormComponent,
    ImageCarouselComponent,
    LoginFormComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit, OnDestroy {
  cars: Car[] = [];
  search: string = '';
  sort: string = '';
  loading: boolean = true;
  updating: boolean = false;
  user: User | null = null;
  showLogin: boolean = false;
  showCarForm: boolean = false;
  editingCar: Car | null = null;
  isSubmitting: boolean = false;
  formKey: number = 0;
  carsWithImagesLoading: Set<number> = new Set();
  selectedCar: Car | null = null;
  isCarDetailView: boolean = false;

  private carsUpdatedListener = () => this.fetchCars();
  private carImagesUploadedListener = (event: Event) =>
    this.handleCarImagesUploaded(event as CustomEvent);

  constructor(private auth: Auth, private carService: CarService) {}

  ngOnInit() {
    this.initializeApp();
  }

  ngOnDestroy() {
    window.removeEventListener('carsUpdated', this.carsUpdatedListener);
    window.removeEventListener('carImagesUploaded', this.carImagesUploadedListener);
  }

  private initializeApp() {
    const savedUser = this.auth.getUser<{ username: string; role: string } | null>();
    if (this.auth.isLoggedIn() && savedUser) {
      this.user = savedUser;
    }

    this.fetchCars();

    window.addEventListener('carsUpdated', this.carsUpdatedListener);
    window.addEventListener('carImagesUploaded', this.carImagesUploadedListener);
  }

  private handleCarImagesUploaded(event: CustomEvent) {
    const carId = event.detail.carId;
    const status = event.detail.status || 'completed';

    if (status === 'loading') {
      this.carsWithImagesLoading.add(carId);
    } else if (status === 'completed') {
      this.carsWithImagesLoading.delete(carId);
      this.fetchCars();
    }
  }

  async fetchCars() {
    this.loading = true;
    this.updating = true;

    try {
      const data = await this.carService.list();
      this.cars = data.map((car: any) => ({
        ...car,
        createdAt: car.createdAt ? new Date(car.createdAt) : undefined,
        updatedAt: car.updatedAt ? new Date(car.updatedAt) : undefined,
      })) as Car[];
    } catch (error) {
      console.error('Error fetching cars');
    } finally {
      this.loading = false;
      this.updating = false;
    }
  }

  async handleRemoveImage(carId: number, imageUrl: string) {
    try {
      this.updating = true;
      const token = this.auth.getToken() || '';
      await this.carService.removeImage(carId, imageUrl, token);
    } catch (e) {
      alert('Network error');
    } finally {
      await this.fetchCars();
    }
  }

  handleLogin(loginData: any) {
    this.user = { username: loginData.username, role: loginData.role };
    this.showLogin = false;
  }

  async handleLogout() {
    await this.auth.logout();
    this.user = null;
  }

  async handleDeleteCar(carId: number) {
    if (!confirm('Are you sure you want to delete this car?')) return;

    try {
      this.cars = this.cars.filter((car) => car.id !== carId);
      const token = this.auth.getToken() || '';
      await this.carService.remove(carId, token);
    } catch (error) {
      this.fetchCars();
      alert('Network error');
    }
  }

  handleCarSubmit() {
    if (this.isSubmitting) return;
    if (this.showCarForm === false && !this.editingCar) return;

    this.isSubmitting = true;

    if (this.editingCar) {
      this.editingCar = null;
    } else {
      this.showCarForm = false;
      this.formKey++;
    }

    this.editingCar = null;
    this.fetchCars();

    setTimeout(() => {
      this.isSubmitting = false;
    }, 100);
  }

  handleEditCar(car: Car) {
    this.editingCar = {
      ...car,
      createdAt: car.createdAt ? new Date(car.createdAt) : undefined,
      updatedAt: car.updatedAt ? new Date(car.updatedAt) : undefined,
    };
  }

  handleCancelEdit() {
    this.editingCar = null;
    this.formKey++;
  }

  handleAddCar() {
    if (this.showCarForm) {
      return;
    }
    this.formKey = 0;
    this.showCarForm = true;
  }

  get filteredCars(): Car[] {
    return this.cars
      .filter(
        (car) =>
          car.brand.toLowerCase().includes(this.search.toLowerCase()) ||
          car.model.toLowerCase().includes(this.search.toLowerCase())
      )
      .sort((a, b) => {
        if (!this.sort) return 0;
        if (this.sort === 'price-asc') return a.price - b.price;
        if (this.sort === 'price-desc') return b.price - a.price;
        if (this.sort === 'year-asc') return a.productionYear - b.productionYear;
        if (this.sort === 'year-desc') return b.productionYear - a.productionYear;
        return 0;
      });
  }

  trackByCarId(index: number, car: Car): number {
    return car.id;
  }

  handleCarClick(car: Car) {
    this.selectedCar = {
      ...car,
      createdAt: car.createdAt ? new Date(car.createdAt) : undefined,
      updatedAt: car.updatedAt ? new Date(car.updatedAt) : undefined,
    };
    this.isCarDetailView = true;
  }

  handleBackToList() {
    this.selectedCar = null;
    this.isCarDetailView = false;
  }

  handleImageClick(imageUrl: string) {
    // In listing view, clicking on image shows modal (handled by carousel component)
    // In detail view, clicking on image also shows modal
    // No navigation needed - modal is handled by the carousel component itself
  }
}

<div class="p-4 min-h-screen bg-zinc-900">
  <div class="mx-auto max-w-4xl">
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl font-bold text-white">Car Dealership</h1>
      <div class="flex gap-2">
        <div *ngIf="user; else loginButton">
          <span class="text-sm text-zinc-300">
            Welcome, {{ user.username }} ({{ user.role }})
          </span>

          <button
            *ngIf="user.role === 'ADMIN'"
            (click)="handleAddCar()"
            [disabled]="isSubmitting"
            class="px-4 py-2 ml-2 text-white bg-green-500 rounded hover:bg-green-600 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Add Car
          </button>
          <button
            (click)="handleLogout()"
            class="px-4 py-2 ml-2 text-white bg-red-500 rounded hover:bg-red-600"
          >
            Logout
          </button>
        </div>

        <ng-template #loginButton>
          <button
            (click)="showLogin = true"
            class="px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-600"
          >
            Admin Login
          </button>
        </ng-template>
      </div>
    </div>

    <app-login-form *ngIf="showLogin" (onLogin)="handleLogin($event)"></app-login-form>

    <div *ngIf="showCarForm && formKey === 0">
      <app-car-form
        [car]="null"
        (onSubmit)="handleCarSubmit()"
        (onCancel)="showCarForm = false"
      ></app-car-form>
    </div>

    <div *ngIf="!isCarDetailView" class="flex flex-col gap-4 mb-6 md:flex-row">
      <input
        type="text"
        placeholder="Search brand/model..."
        [(ngModel)]="search"
        class="p-2 w-full rounded border md:w-1/2"
      />
      <select [(ngModel)]="sort" class="p-2 w-full rounded border md:w-1/2">
        <option value="">Sort by...</option>
        <option value="price-asc">Price ascending</option>
        <option value="price-desc">Price descending</option>
        <option value="year-asc">Year ascending</option>
        <option value="year-desc">Year descending</option>
      </select>
    </div>

    <div *ngIf="loading" class="text-center text-white">Loading...</div>
    <div *ngIf="updating && !loading" class="text-center text-white">Updating...</div>

    <div *ngIf="isCarDetailView && selectedCar" class="mb-6">
      <button
        (click)="handleBackToList()"
        class="flex gap-2 items-center px-4 py-2 mb-4 text-white bg-blue-500 rounded hover:bg-blue-600"
      >
        ← Back to listings
      </button>

      <div class="p-6 rounded-lg border shadow-md bg-zinc-800 border-zinc-700">
        <div class="flex justify-between items-start mb-6">
          <h2 class="mb-2 text-3xl font-bold text-white">
            {{ selectedCar.brand }} {{ selectedCar.model }}
          </h2>
          <div class="text-2xl font-bold text-white">${{ selectedCar.price }}</div>
        </div>

        <!-- Images Gallery -->
        <div class="mb-8">
          <app-image-carousel
            *ngIf="selectedCar.imageGallery && selectedCar.imageGallery.length > 0"
            [images]="selectedCar.imageGallery"
            [carId]="selectedCar.id"
            [isAdmin]="user?.role === 'ADMIN'"
            (onRemoveImage)="handleRemoveImage(selectedCar.id, $event)"
            (onImageClick)="handleImageClick($event)"
          ></app-image-carousel>

          <div
            *ngIf="!selectedCar.imageGallery || selectedCar.imageGallery.length === 0"
            class="flex justify-center items-center h-64 rounded-lg bg-zinc-700"
          >
            <div class="text-center text-zinc-400">
              <div>No images available</div>
            </div>
          </div>
        </div>

        <!-- Specifications -->
        <div class="mt-8">
          <h3 class="mb-4 text-xl font-semibold text-white">Specifications</h3>
          <div class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
            <div class="text-zinc-300">
              <span class="font-medium">Production Year:</span>
              <div class="text-white">{{ selectedCar.productionYear }}</div>
            </div>
            <div class="text-zinc-300">
              <span class="font-medium">Fuel Type:</span>
              <div class="text-white">{{ selectedCar.fuelType }}</div>
            </div>
            <div class="text-zinc-300">
              <span class="font-medium">Mileage:</span>
              <div class="text-white">{{ selectedCar.mileage }} km</div>
            </div>
            <div class="text-zinc-300">
              <span class="font-medium">Engine Capacity:</span>
              <div class="text-white">{{ selectedCar.engineCapacity }} L</div>
            </div>
            <div class="text-zinc-300">
              <span class="font-medium">Transmission:</span>
              <div class="text-white">{{ selectedCar.transmission }}</div>
            </div>
            <div class="text-zinc-300">
              <span class="font-medium">Added:</span>
              <div class="text-white">{{ selectedCar.createdAt | date : 'medium' }}</div>
            </div>
            <div class="text-zinc-300">
              <span class="font-medium">Last Updated:</span>
              <div class="text-white">{{ selectedCar.updatedAt | date : 'medium' }}</div>
            </div>
          </div>
        </div>

        <!-- Description -->
        <div *ngIf="selectedCar.description" class="mt-8">
          <h3 class="mb-4 text-xl font-semibold text-white">Description</h3>
          <p class="leading-relaxed text-zinc-300">{{ selectedCar.description }}</p>
        </div>

        <!-- Admin Controls -->
        <div *ngIf="user && user.role === 'ADMIN'" class="flex gap-2 mt-8">
          <button
            (click)="handleEditCar(selectedCar); handleBackToList()"
            class="px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-600"
          >
            Edit Car
          </button>
          <button
            (click)="handleDeleteCar(selectedCar.id); handleBackToList()"
            class="px-4 py-2 text-white bg-red-500 rounded hover:bg-red-600"
          >
            Delete Car
          </button>
        </div>
      </div>
    </div>

    <!-- Car List View -->
    <div *ngIf="!isCarDetailView && !loading && !updating" class="grid gap-4">
      <div *ngIf="filteredCars.length === 0" class="text-center text-white">No listings found.</div>

      <div
        *ngFor="let car of filteredCars; trackBy: trackByCarId"
        class="p-4 rounded border shadow bg-zinc-800 border-zinc-700"
      >
        <app-car-form
          *ngIf="editingCar && editingCar.id === car.id"
          [car]="car"
          (onSubmit)="handleCarSubmit()"
          (onCancel)="handleCancelEdit()"
        ></app-car-form>

        <div
          *ngIf="!editingCar || editingCar.id !== car.id"
          class="transition-colors cursor-pointer hover:bg-zinc-700 hover:rounded-md"
          (click)="handleCarClick(car)"
        >
          <div class="flex gap-4">
            <!-- Gallery on the left -->
            <div class="flex-shrink-0 w-48">
              <div *ngIf="car.imageGallery && car.imageGallery.length > 0">
                <app-image-carousel
                  [images]="car.imageGallery"
                  [carId]="car.id"
                  [isAdmin]="user?.role === 'ADMIN'"
                  [showThumbnails]="false"
                  (onRemoveImage)="handleRemoveImage(car.id, $event)"
                  (onImageClick)="handleImageClick($event)"
                ></app-image-carousel>
              </div>

              <div
                *ngIf="carsWithImagesLoading.has(car.id)"
                class="flex justify-center items-center w-48 h-36 rounded-lg bg-zinc-700"
              >
                <div class="text-center text-zinc-400">
                  <div
                    class="mx-auto mb-2 w-8 h-8 rounded-full border-b-2 border-blue-500 animate-spin"
                  ></div>
                  <div class="text-xs">Loading...</div>
                </div>
              </div>

              <div
                *ngIf="!car.imageGallery || car.imageGallery.length === 0"
                class="flex justify-center items-center w-48 h-36 rounded-lg bg-zinc-700"
              >
                <div class="text-center text-zinc-400">
                  <div class="text-xs">No images</div>
                </div>
              </div>
            </div>

            <!-- Car details -->
            <div class="flex-1">
              <div class="flex justify-between items-start mb-3">
                <div class="text-lg font-bold text-white">{{ car.brand }} {{ car.model }}</div>

                <div class="flex gap-4 items-center">
                  <div class="text-lg font-bold text-white">${{ car.price }}</div>

                  <div
                    *ngIf="user && user.role === 'ADMIN'"
                    class="flex gap-2"
                    (click)="$event.stopPropagation()"
                  >
                    <button
                      (click)="handleEditCar(car)"
                      class="px-3 py-1 text-sm text-white bg-blue-500 rounded hover:bg-blue-600"
                    >
                      Edit
                    </button>
                    <button
                      (click)="handleDeleteCar(car.id)"
                      class="px-3 py-1 text-sm text-white bg-red-500 rounded hover:bg-red-600"
                    >
                      Delete
                    </button>
                  </div>
                </div>
              </div>

              <div class="grid grid-cols-2 gap-2 text-sm text-zinc-300 md:grid-cols-3">
                <div>
                  Production Year:
                  <span class="font-medium text-white">{{ car.productionYear }}</span>
                </div>

                <div>
                  Fuel Type: <span class="font-medium text-white">{{ car.fuelType }}</span>
                </div>
                <div>
                  Mileage: <span class="font-medium text-white">{{ car.mileage }} km</span>
                </div>
                <div>
                  Engine Capacity:
                  <span class="font-medium text-white">{{ car.engineCapacity }} L</span>
                </div>
                <div>
                  Transmission:
                  <span class="font-medium text-white">{{ car.transmission }}</span>
                </div>
                <div>
                  Added:
                  <span class="font-medium text-white">{{ car.createdAt | date : 'short' }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<ng-template #noImages>
  <div
    class="flex flex-shrink-0 justify-center items-center w-32 h-24 rounded border border-zinc-600 bg-zinc-700"
  >
    <div class="text-center text-zinc-400">
      <div class="text-xs">No images</div>
    </div>
  </div>
</ng-template>

<ng-template #noGallery>
  <div class="flex justify-center items-center h-64 rounded-lg bg-zinc-700">
    <div class="text-center text-zinc-400">
      <div>No images available</div>
    </div>
  </div>
</ng-template>

// frontend/src/App.jsx
import { useCallback, useEffect, useState } from "react";
import "./App.css";
import CarForm from "./components/CarForm";
import ImageCarousel from "./components/ImageCarousel";
import LoginForm from "./components/LoginForm";

function App() {
  const [cars, setCars] = useState([]);
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState("");
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);
  const [user, setUser] = useState(null);
  const [showLogin, setShowLogin] = useState(false);
  const [showCarForm, setShowCarForm] = useState(false);
  const [editingCar, setEditingCar] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formKey, setFormKey] = useState(0);
  const [carsWithImagesLoading, setCarsWithImagesLoading] = useState(new Set());

  useEffect(() => {
    const token = localStorage.getItem("token");
    const savedUser = localStorage.getItem("user");
    if (token && savedUser) {
      setUser(JSON.parse(savedUser));
    }
    fetchCars();

    const handleCarsUpdated = () => {
      fetchCars();
      setCarsWithImagesLoading(new Set());
    };

    const handleCarImagesUploaded = (event) => {
      const carId = event.detail.carId;
      const status = event.detail.status || "completed";

      if (status === "loading") {
        setCarsWithImagesLoading((prev) => {
          const newSet = new Set(prev);
          newSet.add(carId);
          return newSet;
        });
      } else if (status === "completed") {
        setCarsWithImagesLoading((prev) => {
          const newSet = new Set(prev);
          newSet.delete(carId);
          return newSet;
        });

        fetchCars();
      }
    };

    window.addEventListener("carsUpdated", handleCarsUpdated);
    window.addEventListener("carImagesUploaded", handleCarImagesUploaded);

    return () => {
      window.removeEventListener("carsUpdated", handleCarsUpdated);
      window.removeEventListener("carImagesUploaded", handleCarImagesUploaded);
    };
  }, []);

  useEffect(() => {}, [showCarForm]);

  useEffect(() => {}, [formKey]);

  useEffect(() => {
    if (formKey > 0) {
      setShowCarForm(false);
    }
  }, [formKey]);

  const fetchCars = useCallback(async () => {
    setLoading(true);
    setUpdating(true);
    try {
      const res = await fetch("http://localhost:8080/api/cars");
      const data = await res.json();
      setCars(data);
    } catch {
      console.error("Error fetching cars");
    } finally {
      setLoading(false);
      setUpdating(false);
    }
  }, []);

  const handleRemoveImage = useCallback(() => {
    setUpdating(true);
    fetchCars();
  }, [fetchCars]);

  const handleLogin = (loginData) => {
    setUser({ username: loginData.username, role: loginData.role });
    setShowLogin(false);
  };

  const handleLogout = async () => {
    try {
      const token = localStorage.getItem("token");
      await fetch("http://localhost:8080/api/auth/logout", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
    } catch {
      console.error("Logout error");
    } finally {
      localStorage.removeItem("token");
      localStorage.removeItem("user");
      setUser(null);
    }
  };

  const handleDeleteCar = async (carId) => {
    if (!confirm("Are you sure you want to delete this car?")) return;
    try {
      setCars((prevCars) => prevCars.filter((car) => car.id !== carId));
      const response = await fetch(`http://localhost:8080/api/cars/${carId}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      });
      if (!response.ok) {
        fetchCars();
        alert("Error deleting car");
      }
    } catch {
      fetchCars();
      alert("Network error");
    }
  };

  const handleCarSubmit = () => {
    if (isSubmitting) {
      return;
    }

    if (showCarForm === false && !editingCar) {
      return;
    }

    setIsSubmitting(true);

    if (editingCar) {
      setEditingCar(null);
    } else {
      setShowCarForm(false);

      setFormKey((prev) => prev + 1);
    }

    setEditingCar(null);

    fetchCars();

    setTimeout(() => {
      setIsSubmitting(false);
    }, 100);
  };

  const handleEditCar = (car) => {
    setEditingCar(car);
  };

  const handleCancelEdit = () => {
    setEditingCar(null);
    setFormKey((prev) => prev + 1);
  };

  const filteredCars = cars
    .filter(
      (car) =>
        car.brand.toLowerCase().includes(search.toLowerCase()) ||
        car.model.toLowerCase().includes(search.toLowerCase())
    )
    .sort((a, b) => {
      if (!sort) return 0;
      if (sort === "price-asc") return a.price - b.price;
      if (sort === "price-desc") return b.price - a.price;
      if (sort === "year-asc") return a.productionYear - b.productionYear;
      if (sort === "year-desc") return b.productionYear - a.productionYear;
      return 0;
    });

  return (
    <div className="p-4 min-h-screen bg-zinc-900">
      <div className="mx-auto max-w-4xl">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-white">Car Dealership</h1>
          <div className="flex gap-2">
            {user ? (
              <>
                <span className="text-sm text-zinc-300">
                  Welcome, {user.username} ({user.role})
                </span>
                {user.role === "ADMIN" && (
                  <button
                    onClick={() => {
                      if (showCarForm) {
                        return;
                      }
                      setFormKey(0);
                      setShowCarForm(true);
                    }}
                    disabled={isSubmitting}
                    className="px-4 py-2 text-white bg-green-500 rounded hover:bg-green-600 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Add Car
                  </button>
                )}
                <button
                  onClick={handleLogout}
                  className="px-4 py-2 text-white bg-red-500 rounded hover:bg-red-600"
                >
                  Logout
                </button>
              </>
            ) : (
              <button
                onClick={() => setShowLogin(true)}
                className="px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-600"
              >
                Admin Login
              </button>
            )}
          </div>
        </div>

        {showLogin && <LoginForm onLogin={handleLogin} />}

        {showCarForm && formKey === 0 && (
          <div>
            <CarForm
              key={`new-car-form-${formKey}`}
              car={null}
              onSubmit={() => {
                handleCarSubmit();
              }}
              onCancel={() => {
                setShowCarForm(false);
              }}
            />
          </div>
        )}

        <div className="flex flex-col gap-4 mb-6 md:flex-row">
          <input
            type="text"
            placeholder="Search brand/model..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="p-2 w-full rounded border md:w-1/2"
          />
          <select
            value={sort}
            onChange={(e) => setSort(e.target.value)}
            className="p-2 w-full rounded border md:w-1/2"
          >
            <option value="">Sort by...</option>
            <option value="price-asc">Price ascending</option>
            <option value="price-desc">Price descending</option>
            <option value="year-asc">Year ascending</option>
            <option value="year-desc">Year descending</option>
          </select>
        </div>
        {loading ? (
          <div className="text-center text-white">Loading...</div>
        ) : updating ? (
          <div className="text-center text-white">Updating...</div>
        ) : (
          <div className="grid gap-4">
            {filteredCars.length === 0 ? (
              <div className="text-center text-white">No listings found.</div>
            ) : (
              filteredCars.map((car) => (
                <div key={car.id} className="p-4 rounded border shadow bg-zinc-800 border-zinc-700">
                  {editingCar && editingCar.id === car.id ? (
                    <CarForm
                      key={`edit-car-${car.id}-${formKey}`}
                      car={car}
                      onSubmit={handleCarSubmit}
                      onCancel={handleCancelEdit}
                    />
                  ) : (
                    <>
                      <div className="flex gap-4">
                        {car.imageGallery && car.imageGallery.length > 0 ? (
                          <div className="flex-shrink-0">
                            <img
                              src={car.imageGallery[0]}
                              alt={`${car.brand} ${car.model}`}
                              className="object-cover w-32 h-24 rounded border border-zinc-600"
                            />
                          </div>
                        ) : carsWithImagesLoading.has(car.id) ? (
                          <div className="flex flex-shrink-0 justify-center items-center w-32 h-24 rounded border border-zinc-600 bg-zinc-700">
                            <div className="text-center text-zinc-400">
                              <div className="mx-auto mb-2 w-8 h-8 rounded-full border-b-2 border-blue-500 animate-spin"></div>
                              <div className="text-xs">Loading images...</div>
                            </div>
                          </div>
                        ) : (
                          <div className="flex flex-shrink-0 justify-center items-center w-32 h-24 rounded border border-zinc-600 bg-zinc-700">
                            <div className="text-center text-zinc-400">
                              <div className="mb-1 text-2xl">📷</div>
                              <div className="text-xs">No images</div>
                            </div>
                          </div>
                        )}
                        <div className="flex-1">
                          <div className="flex justify-between items-start mb-3">
                            <div className="text-lg font-bold text-white">
                              {car.brand} {car.model}
                            </div>
                            {user && user.role === "ADMIN" && (
                              <div className="flex gap-2">
                                <button
                                  onClick={() => handleEditCar(car)}
                                  className="px-3 py-1 text-sm text-white bg-blue-500 rounded hover:bg-blue-600"
                                >
                                  Edit
                                </button>
                                <button
                                  onClick={() => handleDeleteCar(car.id)}
                                  className="px-3 py-1 text-sm text-white bg-red-500 rounded hover:bg-red-600"
                                >
                                  Delete
                                </button>
                              </div>
                            )}
                          </div>
                          <div className="grid grid-cols-2 gap-2 text-sm text-zinc-300 md:grid-cols-3">
                            <div>
                              Production Year:{" "}
                              <span className="font-medium text-white">{car.productionYear}</span>
                            </div>
                            <div>
                              Price: <span className="font-medium text-white">${car.price}</span>
                            </div>
                            <div>
                              Fuel Type:{" "}
                              <span className="font-medium text-white">{car.fuelType}</span>
                            </div>
                            <div>
                              Mileage:{" "}
                              <span className="font-medium text-white">{car.mileage} km</span>
                            </div>
                            <div>
                              Engine Capacity:{" "}
                              <span className="font-medium text-white">{car.engineCapacity} L</span>
                            </div>
                          </div>

                          {/* Image Carousel */}
                          {car.imageGallery && car.imageGallery.length > 0 ? (
                            <ImageCarousel
                              images={car.imageGallery}
                              onRemoveImage={handleRemoveImage}
                              carId={car.id}
                              isAdmin={user?.role === "ADMIN"}
                            />
                          ) : carsWithImagesLoading.has(car.id) ? (
                            <div className="mt-4">
                              <h3 className="mb-3 text-lg font-semibold text-white">
                                Image Gallery
                              </h3>
                              <div className="flex justify-center items-center h-64 rounded-lg bg-zinc-700">
                                <div className="text-center text-zinc-400">
                                  <div className="mx-auto mb-3 w-12 h-12 rounded-full border-b-2 border-blue-500 animate-spin"></div>
                                  <div>Uploading images...</div>
                                </div>
                              </div>
                            </div>
                          ) : (
                            <div className="mt-4">
                              <h3 className="mb-3 text-lg font-semibold text-white">
                                Image Gallery
                              </h3>
                              <div className="flex justify-center items-center h-64 rounded-lg bg-zinc-700">
                                <div className="text-center text-zinc-400">
                                  <div className="mb-2 text-4xl">📷</div>
                                  <div>No images available</div>
                                </div>
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    </>
                  )}
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default App;
